apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 3.26.8
    chart: argo-cd
    helm:
      valueFiles:
      values: |-
        installCRDs: false
        dex:
          enabled: false
        server:
          extraArgs:
            - --insecure
          config:
            repositories: |
              - type: helm
                name: stable
                url: https://charts.helm.sh/stable
              - type: helm
                name: argo-cd
                url: https://argoproj.github.io/argo-helm
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
    - CreateNamespace=true  
    automated:
      prune: true
      selfHeal: true