apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd-local
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 3.33.3
    chart: argo-cd
    alias: argocd
    helm:
      values: |-
        installCRDs: false
        dex:
          enabled: false
        server:
          extraArgs:
            - --insecure
          config:
            repositories: |
              - type: helm
                name: stable
                url: https://charts.helm.sh/stable
              - type: helm
                name: argocd
                url: https://argoproj.github.io/argo-helm
  destination:
    namespace: argocd-local
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
    - CreateNamespace=true  
    automated:
      prune: true
      selfHeal: true